#!/bin/bash


#  OSL740 Assignment 1 configuration check
#  Written by: Peter Callaghan, modified by Eric Brauer
#  Last Modified: 2023-06-09
#  This script runs a series of commands to determine if you have complete the tasks
#  in assignment 1.  It will create a text file in your home directory called a1.submission.

if [ $USER != 'root' ] && [ $(whoami) != 'root' ]
then
  echo 'You must run this shell script with elevated permissions.' >&2
  exit 1
fi

echo 'Run this script on the VM you have created for the assignment (not C7Host). Press Enter to proceed or Ctrl+C to cancel.'
read
user=$(who am i | awk '{print $1}')
userdir=$(grep "${user}" /etc/passwd | head -1 | cut -d: -f6)
username=$(grep "${user}" /etc/passwd | head -1 | cut -d: -f1)
cat <<'PPC' > /tmp/osl740.pub
-----BEGIN PGP PUBLIC KEY BLOCK-----

mQGNBGSD2HoBDACmrfPWFJrsR8K7adr8RQMGtpU1ycMWNy6eslQmdqreX3fmivrP
70bTEJVp4bDZv5jM31KNFBIH2Jqb+8kbSTnWRwuNnEcYF3fGJ2NT4Uk0w8e1kzVQ
cx8l80qYOUbIucy4vhVoGTMt64lB6qq5y0eu5MNUY3A/e+Va/h/MApz0oa0CfG6d
mCbjTCgPbgQk9RczODORpHG1e/iqVOzsOC9l7Ysy5Rtjc1Vjlm6mueeE91r4Hsza
IzaGEKuWF+sPaLD67P/ji9TB7zzD7ShShZOEeLFJBbDZMWVQOhS3QNdB2+zy40yQ
SeRk4qwyHULE9euiitiEiktd4pEj5fJYrPfNOy7fQ876sZDNK/N42mbtWQiIjqdj
7K8P/K+5NmvejK9AEiCDzHom+DiVIiciA89C3phEzAauC8N84TshaVZRD+oR5NsV
saSOnqTpDPY45VLiSFQjy63GtLJgLwvNHuHjXDJH6D2z8wgk7TnmRcw1MS1HcVxl
kX5gcIGvWZI4Be8AEQEAAbQ3RXJpYyBCcmF1ZXIgKGZvciBPU0w3NDApIDxlcmlj
LmJyYXVlckBzZW5lY2Fjb2xsZWdlLmNhPokB1AQTAQoAPhYhBD97v7vm2D1uE3JO
N4XGh3lazQviBQJkg9h6AhsDBQkAnjQABQsJCAcCBhUKCQgLAgQWAgMBAh4BAheA
AAoJEIXGh3lazQvinpEL/3A73UsEt0YZWEDLHg2SG6A8FK8XkWHXfmrfW677yT22
GcZqKL8xMPTaUQDL6d/hhh/P9d5nW+cB0d+XtrbHUxMpkIe9FokdFq6JdZnFdBip
Gx1Mb1QhrdBfnW3eFlT7JRySpQtB3pkmhG7Nhm0dzI6+wWg313Qb3808tiC8XGr2
D9BvbBoGMrY3VWEJMx8GQ3xgXhI7DqhbblOFNXQQKAw0xbzGJ0iwwxgU9Zd2OIsH
hugpOYkFHBoP7jax5+m2+Am4ZokzeR8B69OQtcsX28jCksNBJuimUOoS6QAqMMNr
hEqXFg/Yb3CDeQtYyQve2h39cbwcdKUTYKmz6qcs9FIHLHNR+hkn3ncnYlyVw3lP
rvteJ4NR7kBbc+NxgZtvhEZIebDWxtiDBe6iJmMXXmqwyS6UW4vm+OksFDk17onF
F8gPnb75Z4R09ucYBbh9NxvHZWQFrTsnLMpotwjkLfgxvpDqDfKRJylJngMWADvr
F2RVTweGN7cUozkVhJU0UbkBjQRkg9h6AQwAt/jjOna9fE6ALOXrXnzAAzoNR9to
A05Oq/yCgVL6cgt1sHPLyCrtoLI0BMxdDvn55Pu7P3LRPm00UUTw4b1IlWH7OXQ1
aE5mVofpbRxudRl5dkgV8Wp9h4ijiIGfdthduDCiRadOZkOIryunP6qLkAeVgJqw
IOtYrD9QiRuNewjXs5/W6C8NhERl/ov6NPKg2q/5pO3ns89R9MJfoMjD7IW1BUqv
JbR8NB4KmXpgt9l+RrUv/SiizcctAuBq2yvxGCRvsEL+2695x0F+rJdJu+DCLuMd
dblhgy7iBfbOsN0eH6h1QfPUtaKxjvNgU9ssKvqj6s4O78BQ18/AlOrfiRCvHlJI
WLclE3qxHYdJ91m6m8ThcDlozgyddrRdOf9dBM3mSlfFXNaBNbd6mqhSl/4jdt3j
4KujzZGUW53jVaAD+1ipnNTilYfqo21v0IZOhaQnv5dEB+rwWGQZvyjuK+XVu+aJ
OlvAa6QrC/5Tg0tSwyDoDRFgBo6QQb2cH5+HABEBAAGJAbwEGAEKACYWIQQ/e7+7
5tg9bhNyTjeFxod5Ws0L4gUCZIPYegIbDAUJAJ40AAAKCRCFxod5Ws0L4km4C/9f
6gpeisvW4R4aZm8neRyZ15OEw802eM/rBgui3rfzL2ynPBp6mDb2+g/8bn1ZOQMG
nJ5l9kNuyJgcm8LKKB+p7xkY7nqM/1uBNE2L97nfgPbxRutxZes1zYxGHeilHCKv
3QurAFG8TZy+xbcPxK5fgGNYB0M44/oBvvxUPhVnmyzXhmU0MghsChez53BNrg0m
9MiHLpey9C+geUbgn6gSZPWcFx8hZUqcY+c2lp+dbHpyrOrfDP7to5wiHuiFiNwr
RFHrvZqrC28122bTFhI3g4459U32Fq67c31KKMJsrO2YEFuD0rTYQBzUfF50NYJk
kls1y6sIUYvhLA1hGrb2MvxOU1eW/MSYyqvhE25w04m3yGSysfFhcUM4o8c5YleJ
MagHXRRA71lIJvHtLbBeIv8bQa7HGIEj0IXFxM1ywdq2CpkO1wJDqIewuZ2G+M7c
h4VbJTn+Xx8dQnVBf/71BbyQ9sJ0OsS5US0pg14rz4xD3iOFb9ddgVBu1gDnxDI=
=ql1W
-----END PGP PUBLIC KEY BLOCK-----
PPC

cat <<'PPC' > /tmp/checkassign1.bash
#!/bin/bash
echo date: `date`
echo hostname: `hostname` 
echo ""
echo VOLUMES 
df -hT 
echo SEMULOV 
echo "" 
echo UUIDS
blkid | sed -r 's/^.*UUID=\"([a-zA-Z0-9\-]+)\".*$/\1/'
echo SDIUU
echo ""
echo PASSWD 
cat /etc/passwd 
echo DWSSAP 
echo "" 
echo GROUP 
cat /etc/group 
echo PUORG 
echo "" 
echo SUDOERS 
sed -re '/^[[:space:]]*#/ d' -e '/^[[:space:]]*$/ d' /etc/sudoers 
echo SROEDUS 
echo "" 
echo SUDOERS.D 
for file in `find /etc/sudoers.d -type f`
do
  if [ -f $file ]
  then
    echo $file 
    cat $file 
    echo "" 
  fi
done
echo D.SROEDUS 
echo "" 
echo "target: " `systemctl get-default` 

echo "PACKAGES" 
yum list installed 
echo "SEGAKCAP" 
PPC

gpg --import /tmp/osl740.pub &> /dev/null
bash /tmp/checkassign1.bash &> $userdir/a1.$username.txt
gpg --encrypt --always-trust --recipient 'Eric Brauer' -o $userdir/a1.$username.submit $userdir/a1.$username.txt &> /dev/null
gpg --delete-key --batch --yes 'Eric Brauer' &> /dev/null
rm -f /tmp/checkassign1.bash
rm -f /tmp/osl740.pub

echo 'The script created two files in your home directory.'
echo "1.  a1.$username.txt - a human-readable copy of the output that you may review."
echo "2.  a1.$username.submit - an encrypted copy of the output to be uploaded to blackboard."
echo "Upload a1.$username.submit to blackboard along with your assignment script."
